site_name: Toy Zombies
site_description: Página Oficial de Toy Zombies
site_url: https://hec-thor-tech.github.io/toy-zombies/

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: img/logo.webp
  favicon: img/icono.webp
  font:
    text: Roboto Mono
    code: Roboto Mono
  palette:
    scheme: slate
    primary: black
    accent: red

# 1. INYECTAR ESTE MÓDULO DE PLUGINS:
nav:
  - Home: index.md
  - Synopsis: lore.md
  - Toy Zombies: bestiario.md
  - Mechanics: mecanicas.md
  - AniMall's Shopping: mapas.md
  - Characters: personajes.md
  - Special Thanks: gracias.md
  - Updates: updates.md

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
        - locale: es
          name: Español
          nav_translations:
            Home: Inicio
            Synopsis: Sinópsis
            Toy Zombies: Toy Zombies
            Mechanics: Mecánicas
            AniMall's Shopping: AniMall's Shopping
            Characters: Personajes
            Special Thanks: Agradecimientos Especiales
            Updates: Actualizaciones

extra_css:
  - stylesheets/extra.css
