site_name: Toy Zombies
site_description: La wiki oficial, el lore y la guía de supervivencia.

theme:
  name: material
  language: es
  # Configuración de colores (Tema oscuro por defecto)
  palette:
    scheme: slate
    primary: black
    accent: red

# Barra de navegación (Menú superior/lateral)
nav:
  - Inicio: index.md
  - Historia: lore.md
  - Toy Zombies: bestiario.md
  - Animalls Shopping: mapas.md
  - Personajes: personajes.md

extra_css:
  - stylesheets/extra.css