site_name: Toy Zombies
site_description: Página Oficial de Toy Zombies

theme:
  name: material
  language: es
  logo: img/logo.png
  favicon: img/icono.webp
  # Esta línea obliga a todos los dispositivos a usar letra de Terminal (Máquina de escribir)
  font:
    text: Roboto Mono
    code: Roboto Mono
  # Configuración de colores (Tema oscuro por defecto)
  palette:
    scheme: slate
    primary: black
    accent: red

# Barra de navegación (Menú superior/lateral)
nav:
  - Inicio: index.md
  - Historia: lore.md
  - Toy Zombies: bestiario.md
  - Animalls Shopping: mapas.md
  - Personajes: personajes.md

extra_css:
  - stylesheets/extra.css